# Spring Properties
spring:
  application:
    name: web-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/


# HTTP Server
server:
  port: 3333

accounts-service:
  ribbon:
    eureka:
      enabled: true
    listOfServers: localhost:2222
    ServerListRefreshInterval: 15000
    #DeploymentContextBasedVipAddresses: accounts-service
    #NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG

#gateway-service:
#  ribbon:
#    eureka:
#      enabled: true
#    listOfServers: localhost:1110
#    ServerListRefreshInterval: 15000